run:
  timeout: 5m
  tests: false

linters:
  enable:
    - govett
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
  disable-all: false

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
